name: gabpipeline

on: 
  push:
    branches:
      - main  # this is the branch we want to trigger

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gab-tetris-app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: actions/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Create namespace
        run: kubectl apply -f k8s/namespace.yml

      - name: Create secret
        run: kubectl apply -f k8s/secret.yml

      - name: Create service account
        run: kubectl apply -f k8s/service-account.yml

      - name: Create role
        run: kubectl apply -f k8s/role.yml

      - name: Create role binding
        run: kubectl apply -f k8s/rolebind.yml

      - name: Deploy application
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml

      - name: Get service details
        run: |
          kubectl get service git-actions-svc -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}' || kubectl get service git-actions-svc -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'
