name: gabpipeline

on: 
  push:
    branches:
      - main  # this is the branch we want to trigger

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ugogabriel/gab-tetris-app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: build_and_push

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: actions/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Configure kubectl
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_TOKEN }}
        run: echo "$KUBE_TOKEN" | base64 --decode > $HOME/.kube/config

      - name: Deploy application
        run: |
          kubectl apply -f k8s-manifest/deployment.yml
          kubectl apply -f k8s-manifest/service.yml

      - name: Get service details
        run: |
          kubectl get service tetris-app -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}' || kubectl get service tetris-app -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'
