name: gabpipeline

on: 
  push:
    branches:
      - main  # this is the branch we want to trigger

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ugogabriel/gab-tetris-app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Authenticate with Kubernetes
        run: |
          echo "$K8S_TOKEN" | kubectl config set-credentials github-actions --token=$(cat -)
          kubectl config set-context kind-kind --cluster=kind-kind --user=github-actions
          kubectl config use-context kind-kind
          kubectl config set-context --current --namespace=tetris-app
        env:
            K8S_TOKEN: ${{ secrets.KUBE_TOKEN }}

      - name: Deploy application
        run: |
          kubectl apply -f k8s-manifest/deployment.yml --validate=false
          kubectl apply -f k8s-manifest/service.yml --validate=false

      - name: Get service details
        run: |
          kubectl get service tetris-app -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}' || kubectl get service tetris-app -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'
