name: gabpipeline

on: 
  push:
    branches:
      - main  # this is the branch we want to trigger

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image.
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ugogabriel/gab-tetris-app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted

    steps:
      - name: Kubectl Action
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_TOKEN }}

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s-manifest/deployment.yml
          kubectl apply -f k8s-manifest/ingress.yml
          kubectl apply -f k8s-manifest/service.yml

      - name: Get Ingress IP
        id: get-ingress-ip
        run: |
          INGRESS_IP=$(kubectl get ingress gab-tetris-app -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "::set-output name=ingress_ip::$INGRESS_IP"

      - name: Output Ingress IP
        run: |
          echo "Ingress IP: ${{ steps.get-ingress-ip.outputs.ingress_ip }}"
        