name: gabpipeline

on: 
  push:
    branches:
      - main  # this is the branch we want to trigger

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ugogabriel/gab-tetris-app:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Configure kubectl
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          echo "$KUBE_CONFIG" | base64 --decode > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Create namespace
        run: kubectl apply -f k8s-manifest/roles/namespace.yml --validate=false

      - name: Create secret
        run: kubectl apply -f k8s-manifest/roles/secret.yml

      - name: Create service account
        run: kubectl apply -f k8s-manifest/roles/service-account.yml

      - name: Create role
        run: kubectl apply -f k8s-manifest/roles/role.yml

      - name: Create role binding
        run: kubectl apply -f k8s-manifest/roles/rolebind.yml

      - name: Deploy application
        run: |
          kubectl apply -f k8s-manifest/deployment.yml
          kubectl apply -f k8s-manifest/service.yml

      - name: Get service details.
        run: |
          kubectl get service tetris-app -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}' || kubectl get service tetris-app -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'
