apiVersion: v1
kind: Service
metadata:
  name: tetris-app
  namespace: tetris-app
spec:
  type: NodePort
  selector:
    app: tetris-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
